### PR TITLE
add commit history and update readme

### PR DESCRIPTION
**Pull request by hughhuangzh**
Address comments: https://github.com/cert-manager/website/pull/930#issuecomment-1109728648

### CODE REVIEW

**Comment by hughhuangzh** [comment]
@johnwalicki can you help to review and merge, thx.

**Comment by johnwalicki** [comment]
This is a large PR. Did you review it all? Would take me a long time.

**Comment by hughhuangzh** [comment]
@johnwalicki just review the new updates.

**Comment by hughhuangzh** [comment]
@johnwalicki can you help to merge, we are stuck here..

**Comment by johnwalicki** [comment]
I've merged this PR.

**Pull request merged**
